kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "mvn -f /home/runner/workspace/backend/pom.xml spring-boot:run"

[services.production]

[services.production.build]
args = ["mvn", "-f", "/home/runner/workspace/backend/pom.xml", "package", "-DskipTests"]

[services.production.run]
args = ["java", "-jar", "/home/runner/workspace/backend/target/bookstore-api-1.0.0.jar"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
